package com.hansholz.bestenotenapp.notifications

/* Pre-generated by AI */
actual object GradeNotifications {
    actual val isSupported: Boolean = false

    actual fun initialize(platformContext: Any?) {
        GradeNotificationNotifier.ensureInitialized(platformContext)
    }
    actual fun refreshScheduling() {}
    actual fun onSettingsUpdated() {}
    actual fun onLogin() {}
    actual fun onLogout() {}
    actual suspend fun requestPermission(): Boolean {
        return false
    }
}
