package com.hansholz.bestenotenapp.notifications

/* Pre-generated by AI */
internal actual object GradeNotificationNotifier {
    actual fun ensureInitialized(platformContext: Any?) {}
    actual fun notifyNewGrades(notifications: List<GradeNotificationPayload>) {}
}
