package com.hansholz.bestenotenapp.components

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.ImageShader
import androidx.compose.ui.graphics.ShaderBrush
import androidx.compose.ui.graphics.TileMode
import androidx.compose.ui.graphics.drawscope.withTransform

@Composable
fun RepeatingBackground(
    imageBitmap: ImageBitmap,
    modifier: Modifier = Modifier,
    scale: Float = 1.0f,
    offset: Offset = Offset.Zero,
) {
    Box(
        modifier.fillMaxSize().repeatingBackground(
            imageBitmap = imageBitmap,
            scale = scale,
            offset = offset,
        ),
    )
}

// Pre-generated by AI
fun Modifier.repeatingBackground(
    imageBitmap: ImageBitmap,
    alpha: Float = 1.0f,
    scale: Float = 1.0f,
    offset: Offset = Offset.Zero,
): Modifier {
    require(scale > 0f) { "Scale must be positive" }

    return this.drawBehind {
        val imageShader = ImageShader(imageBitmap, TileMode.Repeated, TileMode.Repeated)
        val brush = ShaderBrush(imageShader)

        val scaledWidth = imageBitmap.width * scale
        val scaledHeight = imageBitmap.height * scale

        val correctedStartX = (offset.x % scaledWidth).let { if (it > 0) it - scaledWidth else it }
        val correctedStartY = (offset.y % scaledHeight).let { if (it > 0) it - scaledHeight else it }

        withTransform({
            translate(left = correctedStartX, top = correctedStartY)
            scale(scaleX = scale, scaleY = scale, pivot = Offset.Zero)
        }) {
            drawRect(
                brush = brush,
                alpha = alpha,
                size =
                    Size(
                        width = (this.size.width - correctedStartX) / scale,
                        height = (this.size.height - correctedStartY) / scale,
                    ),
            )
        }
    }
}
