package com.hansholz.bestenotenapp.utils

/* Pre-generated by AI */
fun formateInterval(minutes: Long): String {
    return if (minutes % 60L == 0L) {
        val hours = minutes / 60L
        if (hours == 1L) "1 Stunde" else "$hours Stunden"
    } else {
        "$minutes Minuten"
    }
}